### PR TITLE
Include sampling rate when returning continuous date

### PR DESCRIPTION
**Pull request by stinos**
Without the sampling rate the data is pretty meaningless.

### CODE REVIEW

**Comment by cboulay** [comment]
I've been using this library for about 7 years and I've never needed this feature. I hope my data aren't meaningless!

For each channel, the sampling rate **shouldn't** change, so returning the redundant sampling rate 100's or 1000's of times per second is undesirable. Breaking the API for a redundant piece of information is also undesirable, so on that basis alone I'm inclined to reject this.

Could you present a scenario where it's necessary to get the sampling rate with every return? The only thing I can think of is that you are using multiple sampling groups simultaneously (e.g. some channels at 30 kHz, some at 1 kHz) and these data are all being returned together in a single call to `trial_continuous`. In this scenario, I would [identify each channel's sampling group before beginning acquisition](https://github.com/dashesy/CereLink/blob/master/cerebus/cbpy.pyx#L793), and the processing pipeline would group data together based on their sampling groups.

If you for some reason feel the need to change sampling rate for a given channel multiple times in the same acquisition context, then please come up with a different solution. I highly doubt you're doing this, because you can't record data this way. Just in case you are, the better solution would be to keep it the highest sampling rate and when you need lower-rate data just bin-and-average. e.g., sample at 30 kHz and then bin-and-average 30-sample bins to get 1 kHz.

**Comment by stinos** [comment]
> redundant sampling rate

I already had the impression I was missing something so I admit this is the easy solution and I should have asked the question first: what is the proper way to get the current samplingrate of each channel?

> Breaking the API

Adding an element to a list at the end isn't really breaking though, unlike adding return values or so.

> Could you present a scenario where it's necessary to get the sampling rate with every return?

I'm testing online decoding of features and it turns out it's convenient to change continuous acquisition filter/samplingrate while running to quickly try out things. The data doesn't actually get recorded.

> e.g. some channels at 30 kHz, some at 1 kHz

Yes that's always the case.

> keep it at the highest sampling rate and when you need lower-rate data just bin-and-average

That's the alternative yes, just much less convenient. I perfectly understand that's not a reason to change it for everyone though.

**Comment by cboulay** [comment]
> what is the proper way to get the current samplingrate of each channel?

That would be with `get_channel_config(channel_id)['smpgroup']`, but I expect that function to be too slow to run on every pull. It's the kind of thing you run once (for each channel) at the beginning of an acquisition. You could test to see if it's performant enough for you.

>> bin-and-average
> That's the alternative yes, just much less convenient.

I support a lot of software for interfacing with different DAQs (mostly non-invasive EEG) as part of the labstreaminglayer project and I think this is the first time I've heard of someone wanting to change hardware sampling rate on the fly. Smoothing and downsampling, however, is a very common signal processing step and to me is the more convenient option.

**Comment by stinos** [comment]
> That would be with get_channel_config(channel_id)['smpgroup']

Aha. I assume it's guaranteed that 2 = 1kHz, 3 = 2kHz and so on? Is that mapping available in Cerelink somewhere? I wouldn't require this every single pull, just once before a 'block' of a couple of seconds so performance-wise that should be ok.

> downsampling, however, is a very common signal processing step and to me is the more convenient option

Sure, if you can configure it. To do that I'd have to buid an interface on top of what is now a commandline application.

**Comment by cboulay** [comment]
https://github.com/dashesy/CereLink/blob/5eaef3fb0b1eb341fbca4bfd7d3f803967d66b8e/cbmex/cbsdk.h#L231-L239

This isn't really a ground truth though. These are just names for convenience.

The ground truth is that the base rate of 30000 is hard-coded, then many functions will get the `period` for a channel group, and divide the base rate by the period.

https://github.com/dashesy/CereLink/blob/5eaef3fb0b1eb341fbca4bfd7d3f803967d66b8e/cbhwlib/cbhwlib.h#L1889-L1902

And as far as I can tell, the period is pulled directly from parsing the packet from the NSP, but it is based on the sampling group.

If Blackrock were to change their base rate to 60 kHz, and someone updated CereLink to reflect that but kept all the sampling groups the same, then the true rates would be double what they are named. But I'm pretty sure if Blackrock changed the base rate then a lot of things would break, not just Cerelink.

It's probably safe to assume the group->rate mapping is constant.

**Comment by stinos** [comment]
> This isn't really a ground truth though. These are just names for convenience.

Yeah, found those, and `cbSdk_TICKS_PER_SECOND`. But it's not super clear to me whether they are actually used by the NSP itself (as opposed to being used in cbsdk.cpp and cbmex.cpp here, of which I also don't know whether they are in sync with the versions BlackRock has of these, if that even matters).

Would the 'real' ground truth be sysinfo.sysfreq since that seems to come directly from the NSP? So suppose the base rate changes it is probable that `sysfreq  / period` remains correct whereas `cbSdk_TICKS_PER_SECOND / period` needs to be adjusted? In that case would a patch be of interest which exposes `cbSdkGetSampleGroupInfo` so that it's possible to get the period, and as such calculate the rate directly?

> If Blackrock were to change their base rate to 60 kHz

Actually not super unlikely (well perhaps not 60, but just higer than 30). Some of the competition already has higher base rates, and there are even good reasons for that i.e. it's not just marketing (multimodal experiments with audio, sampling spikes at higher rates actually seems worth it - don't recall the exact paper on that one)

**Comment by cboulay** [comment]
In the past when Blackrock has made major changes they have supported changes to CereLink as well. I assume/hope that will be the case going forward. I think we shouldn't spend our time doing pre-emptive work to support changes in the base rate unless we know it's imminent.

**Pull request closed without merging**
