### PR TITLE
cbpy: Use str for label in get_sample_group, not bytes

### PR DESCRIPTION
**Pull request by stinos**
For consistency with label returned by get_channel_config.

### CODE REVIEW

**Comment by cboulay** [comment]
You're probably correct that the labels should be consistent between the two functions. However, we should be careful about assuming utf8. Is it possible to rename channels in CereLink with non-unicode characters?

**Comment by stinos** [comment]
> Is it possible to rename channels in CereLink with non-unicode characters

Yes because set_channel_config allow passing `bytes`. Likewise in other software (e.g. Central) it's possible to enter e.g. `æ` causing `UnicodeDecodeError` when trying to decode that in `get_channel_config`.

So the existing usage of utf-8 in a couple of places in Cerelink is not ideal. While this fix (consistently being incorrect but producing `str` everywhere so the label coming out of different functions is the same) is still better than the current situation imo, perhaps it's better to fix this properly. Just using `bytes` everywhere is not an option due to backwards compatibility. How about an `encoding` argument for these functions? Or a global variable which gets used anywhere needed?

**Comment by cboulay** [comment]
Yes, I meant Central. Basically if someone can enter it in Central then we want that to work in CereLink.

I think an `encoding` kwarg defaulting to 'utf-8', used both in `get_sample_group` and [`get_channel_config`](https://github.com/dashesy/CereLink/blob/master/cerebus/cbpy.pyx#L833) is probably the way to go for now.

I'd rather not add any globals. If anything, I would prefer an environment variable over a global. But a kwarg is probably more flexible for now. Thanks!

**Comment by cboulay** [comment]
I prefer an `encoding='utf-8'` kwarg both in `get_channel_config` and `get_sample_group` if that works for you.

**Comment by stinos** [comment]
Sure, that would be the best solution indeed.

**Comment by stinos** [comment]
Adjusted where appropriate (not in defaultConParams). Don't really know what to do with the comments here because there's no unified style, but this arguments is worth an explanation I think so added it in the 2 places which already have some comment.

**Comment by cboulay** [comment]
This is great, thanks. I haven't tested it but it looks simple enough.

**Comment by cboulay** [comment]
By the way, since you are deep in the guts of CereLink / cbpy and making some improvements, and presumably have easier access to a NSP these days than I do... 
If you have a few minutes then would you mind trying to figure out the sent-comment color mapping? It seems that no matter what I try my comments always show up as black or dark red, effectively invisible or near-invisible in Central's raster view. They are there though!
https://github.com/dashesy/CereLink/blob/master/cerebus/cbpy.pyx#L950-L957
This might not be a cbpy issue, it might be in CereLink itself.

If you don't have the bandwidth to look into this then please don't worry about it. At the moment it's only a minor annoyance.

**Comment by stinos** [comment]
Color mapping works correctly me when treating color argument as TBGR and using Central 7.0.6. I can get any color I want, and passing 255 for T makes it 'transparent' whatever that means here. Just looks like a black line. Other values don't seem to have effect on that one though.

Only tried when running on top of nPLayServer though, but I doubt it's going to be any different with an actual NSP.

**Comment by cboulay** [comment]
Great, thanks so much for checking.

**Comment by stinos** [comment]
No problem. If you'd like other things get tested and it's a sensible amount of work I can usually find some spare time to do it.

**Pull request merged**
